<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="soap"
    nsURI="http://axis.apache.org/emf/soap" nsPrefix="soap">
  <eClassifiers xsi:type="ecore:EDataType" name="Use" instanceClassName="org.apache.axis.constants.Use"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Style" instanceClassName="org.apache.axis.constants.Style"/>
</ecore:EPackage>
