<?xml version="1.0" encoding="UTF-8"?>
<definitions
    targetNamespace="urn:iface.import.test"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:messages="urn:messages.import.test">

<import
    location="test/import_/ImportMessages.wsdl"
    namespace="urn:messages.import.test">
</import>

<portType name="Import">
  <operation name="addEntry">
    <input message="messages:InaddEntryRequest"/>
    <output message="messages:empty"/>
  </operation>

  <operation name="getAddressFromName">
    <input message="messages:IngetAddressFromNameRequest"/>
    <output message="messages:OutgetAddressFromNameResponse"/>
  </operation>
</portType>

</definitions>
