<?xml version="1.0" encoding="UTF-8"?>
<definitions
    targetNamespace="urn:messages.import.test"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:addressTypes="urn:types.import.test">

<import
    location="test/import_/Import.xsd"
    namespace="urn:types.import.test">
</import>

<message name="empty"/>

<message name="InaddEntryRequest">
  <part name="key" type="xsd:string"/>
  <part name="value" type="addressTypes:Address"/>
</message>

<message name="IngetAddressFromNameRequest">
  <part name="key" type="xsd:string"/>
</message>

<message name="OutgetAddressFromNameResponse">
  <part name="value" type="addressTypes:Address"/>
</message>

</definitions>
