<?xml version="1.0" ?>
<definitions name="urn:getPort.wsdl.test"
             targetNamespace="urn:getPort.wsdl.test"
             xmlns:tns="urn:getPort.wsdl.test"
             xmlns:xsd="http://www.w3.org/1999/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">

  <message name="empty"/>

  <portType name="one"/>
  <portType name="two"/>
  <portType name="three"/>

  <binding name="bindingOne" type="tns:one">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
  </binding>
  <binding name="bindingTwo" type="tns:two">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
  </binding>
  <binding name="bindingThree" type="tns:three">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
  </binding>
  <binding name="bindingAnotherOne" type="tns:one">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
  </binding>

  <service name="empty"/>

  <!-- 
  	all services names unique in the enclosing WSDL document - Test
  	Bug 15686
   -->
  <service name="serviceA">
    <documentation>
    Service with all ports unique. /* Test Bug 13407 - embedded comments */
    </documentation>
    <port name="portAOne" binding="tns:bindingOne">
      <soap:address location="http://localhost:8080/axis/services/portAOne"/>
    </port>
    <port name="portATwo" binding="tns:bindingTwo">
      <soap:address location="http://localhost:8080/axis/services/portATwo"/>
    </port>
    <port name="portAThree" binding="tns:bindingThree">
      <soap:address location="http://localhost:8080/axis/services/portAThree"/>
    </port>
  </service>
  
  <service name="serviceB">
    <documentation>
    Service with two ports (portBTwo, portBTwoA) that share the same portType via the same binding.
    </documentation>
    <port name="portBOne" binding="tns:bindingOne">
      <soap:address location="http://localhost:8080/axis/services/portBOne"/>
    </port>
    <port name="portBTwo" binding="tns:bindingTwo">
      <soap:address location="http://localhost:8080/axis/services/portBTwo"/>
    </port>
    <port name="portBTwoA" binding="tns:bindingTwo">
      <soap:address location="http://localhost:8080/axis/services/portBTwoA"/>
    </port>
  </service>
  
  	<service name="serviceC">
    <documentation>
    Service with two ports (portCTwo, portCThree) that share the same portType via different bindings.
    </documentation>
    <port name="portCOne" binding="tns:bindingOne">
      <soap:address location="http://localhost:8080/axis/services/portCOne"/>
    </port>
    <port name="portCTwo" binding="tns:bindingTwo">
      <soap:address location="http://localhost:8080/axis/services/portCTwo"/>
    </port>
    <port name="portCThree" binding="tns:bindingAnotherOne">
      <soap:address location="http://localhost:8080/axis/services/portCThree"/>
    </port>
  </service>

</definitions>

