<?xml version="1.0" ?>

<definitions 
    name="multiple bindings test"
    targetNamespace="urn:multibinding.wsdl.test"
    xmlns:tns="urn:multibinding.wsdl.test"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

  <!-- message declns -->
  <message name="empty"/>

  <!-- port type declns -->
  <portType name="mbPT">
    <operation name="a">
      <input message="tns:empty"/>
      <output message="tns:empty"/>
    </operation>
    <operation name="b">
      <input message="tns:empty"/>
      <output message="tns:empty"/>
    </operation>
  </portType>

  <!-- binding declns -->
  <binding name="bindingNoLit" type="tns:mbPT">
    <soap:binding
        style="rpc"
        transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="a">
      <input>
        <soap:body use="encoded"/>
      </input>
      <output>
        <soap:body use="encoded"/>
      </output>
    </operation>
    <operation name="b">
      <input>
        <soap:body use="encoded"/>
      </input>
      <output>
        <soap:body use="encoded"/>
      </output>
    </operation>
  </binding>

  <binding name="bindingSomeLit" type="tns:mbPT">
    <soap:binding
        style="rpc"
        transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="a">
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="b">
      <input>
        <soap:body use="encoded"/>
      </input>
      <output>
        <soap:body use="encoded"/>
      </output>
    </operation>
  </binding>

  <binding name="bindingAllLit" type="tns:mbPT">
    <soap:binding
        style="rpc"
        transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="a">
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="b">
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <!-- service decln -->
  <service name="mbService">
    <port name="noLiteral" binding="tns:bindingNoLit">
      <soap:address location="http://localhost:8080/axis/services/noLiteral"/>
    </port>
    <port name="someLiteral" binding="tns:bindingSomeLit">
      <soap:address location="http://localhost:8080/axis/services/someLiteral"/>
    </port>
    <port name="allLiteral" binding="tns:bindingAllLit">
      <soap:address location="http://localhost:8080/axis/services/allLiteral"/>
    </port>
  </service>

</definitions>

