/**
 * RefTestServiceTestCase.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis Wsdl2java emitter, and
 * then modified by Rich Scheuerle to add testcase info.
 */

package test.wsdl.refattr;

import org.apache.axis.utils.ClassUtils;

import test.HttpTestUtil;

public class RefTestServiceTestCase extends junit.framework.TestCase {
    public RefTestServiceTestCase(String name) {
        super(name);
    }

    public void testRefTest() throws Exception {
        test.wsdl.refattr.RefTest binding;
        try {
            RefTestServiceLocator loc = new RefTestServiceLocator();
            binding = new RefTestServiceLocator().getRefTest(HttpTestUtil.getTestEndpoint(loc.getRefTestAddress()));
        }
        catch (javax.xml.rpc.ServiceException jre) {
            throw new junit.framework.AssertionFailedError("JAX-RPC ServiceException caught: " + jre );
        }
        
        // The following declarations are used to verify that unmangled classes
        // are generated by Wsdl2Java (not a mangled class like Phone_Type).
        Info info = new Info();
        Phone phone = new Phone();
        phone.setAreaCode(51);
        phone.setExchange("555");
        phone.setNumber(new PhoneNumber());
        info.setPhone(new Phone[] { phone });
        Enum en  = Enum.fromValue("one");
        info.setEnum(en);
        Forward forward  = new Forward();
        forward.setAddress("test");
        info.setForward(forward);
        NoMangle noMangle  = new NoMangle();
        noMangle.setAddress("test");
        info.setNoMangle2(noMangle);
        Example example = new Example();
        example.setAddress("test");
        example.setNumber(new ExampleNumber());
        info.setNoMangle(example);
        
        // The following code ensures that mangling occurred for the Mangle class
//        Mangle_Type mangle_type = new Mangle_Type();
        // TODO: Right now wsdl2java only changes the class name for the element, not the type.
        //       The JAX-RPC spec doen't clearly say if all class names need to be changed or if
        //       one of the conflicting classes can retain its original name.
        Mangle mangle_type = new Mangle();
        // JAX-RPC 1.1 specifies "_Element" as suffix
        Mangle_Element mangle_element = new Mangle_Element();
        mangle_element.setTwo("test");
        info.setMangle(mangle_element);
//        try {
//            Class cls = ClassUtils.forName("test.wsdl.refattr.Mangle");
//            assertTrue("Found unmangled class test.wsdl.refattr.Mangle", false);
//        } catch (Exception e) {
//            // Okay expect to get an exception
//        }

        assertTrue("binding is null", binding != null);
        try {
            binding.test(info);
        } catch (java.rmi.RemoteException re) {
            throw new junit.framework.AssertionFailedError("Remote Exception caught: " + re );
        }
    }
}

