<?xml version="1.0" ?>

<definitions 
    name="ordering"
    targetNamespace="urn:ordering.wsdl.test"
    xmlns:tns="urn:opStylesDoc.wsdl.test"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

  <!-- type defs -->
  <types>
    <xsd:schema targetNamespace="urn:ordering.wsdl.test"
                xmlns:tns="urn:ordering.wsdl.test"
                xmlns:xsd="http://www.w3.org/1999/XMLSchema">


	<xsd:complexType name="ContextType" abstract="true">
           <xsd:sequence>
		 <xsd:element name="a" type="xsd:string"/>
		 <xsd:element name="b" type="xsd:QName" />
	   </xsd:sequence>
           <xsd:attribute name="id" type="xsd:int"/>
	</xsd:complexType>

	<xsd:element name="Context">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="tns:ContextType">
					<xsd:sequence>
						<xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
        
    </xsd:schema>
  </types>

</definitions>

