<definitions name="ImportTestDefinition"
  targetNamespace="http://test.globus.org/importtest"
  xmlns:tns="http://test.globus.org/importtest"
  xmlns:types="http://test.globus.org/types"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

<types>
  <import 
    namespace="http://test.globus.org/types" 
    schemaLocation="../types3/importStringType.xsd"/> 

  <import 
    namespace="http://test.globus.org/otherTypes" 
    schemaLocation="../types3/importOtherType.xsd"/> 

  <schema targetNamespace="http://test.globus.org/bigType"
        xmlns:tns="http://test.globus.org/bigType"
        xmlns:stringType="http://test.globus.org/types"
        xmlns:otherType="http://test.globus.org/otherTypes"
        xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:complexType name="BigType">
      <xsd:sequence>
        <xsd:element name="one" type="xsd:string"/>
        <xsd:element name="two" type="stringType:StringType"/>
	<xsd:element name="three" type="otherType:OtherType"/>
      </xsd:sequence>
    </xsd:complexType>
  </schema>
</types>

</definitions>
